set_property SRC_FILE_INFO {cfile:C:/Users/lenovo/Downloads/Vivado/STA/pin2reg2reg2pin/pin2reg2reg2pin.srcs/constrs_1/new/dig2anPin_Reg.xdc rfile:../../../pin2reg2reg2pin.srcs/constrs_1/new/dig2anPin_Reg.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN E3 IOSTANDARD LVCMOS33} [get_ports clk100mhz]
set_property src_info {type:XDC file:1 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN C17 IOSTANDARD LVCMOS33} [get_ports SCLK_O]
